.MODEL SMALL
.STACK 100H
.DATA
ALERT DB 'ENTER 2 DIGITS WHOSE SUM IS LESS THAN 10$'
FIRST DB 'ENTER THE FIRST DIGIT: $' 
SECOND DB 'ENTER THE SECOND DIGIT: $'
RESULT DB 'THE SUM IS = $'  
.CODE
MAIN PROC
    MOV AX,@DATA
    MOV DS,AX
    
    ;PRINTING THE ALERT MESSAGE
    MOV AH,9
    LEA DX,ALERT
    INT 21H
    
    ;PRINTING NEW LINE
    MOV AH,2
    MOV DL,10
    INT 21H
    MOV DL,13
    INT 21H
    
    ;PRINT THE FIRST STRING
    MOV AH,9
    LEA DX,FIRST
    INT 21H
    
    ;TAKING FIRST DIGIT
    MOV AH,1
    INT 21H
    MOV BL,AL
    
    ;PRINTING NEW LINE
    MOV AH,2
    MOV DL,10
    INT 21H
    MOV DL,13
    INT 21H
    
    ;PRINTING THE 2ND STRING
    MOV AH,9
    LEA DX,SECOND
    INT 21H
    
    ;TAKING 2ND DIGIT
    MOV AH,1
    INT 21H
    MOV BH,AL    
    
    ;PRINTING NEW LINE
    MOV AH,2
    MOV DL,10
    INT 21H
    MOV DL,13
    INT 21H      
    
    ;PRINTING THE 3RD STRING
    MOV AH,9
    LEA DX,RESULT
    INT 21H   
    
    ;ADDING TWO DIGIT
    ADD BL,BH
    
    ;GET ACTUAL VALUE
    SUB BL,48
    
    ;PRINTING THE RESULT
    MOV AH,2
    MOV DL,BL
    INT 21H
    
    EXIT:
    
    MOV AH,4CH
    INT 21H
    MAIN ENDP
END MAIN
    
    
    